Vagrant.configure("2") do |config|
  config.vm.network "public_network",bridge: "enp0s25"
  config.vm.define "server0" do |server0|
    server0.vm.box = "centos/stream8"
    server0.vm.hostname = 'server0'
    server0.vm.box_url = "centos/stream8"
    server0.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "master"]
    end
  end
  config.vm.define "server1" do |server1|
    server1.vm.box = "centos/stream8"
    server1.vm.hostname = 'server1'
    server1.vm.box_url = "centos/stream8"
    server1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "worker0"]
    end
  end

  config.vm.define "server2" do |server2|
    server2.vm.box = "centos/stream8"
    server2.vm.hostname = 'server2'
    server2.vm.box_url = "centos/stream8"
    server2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "worker1"]
    end
  end
end