Vagrant.configure("2") do |config|
  config.vm.define "server0" do |server0|
    master.vm.box = "centos/stream8"
    master.vm.hostname = 'server0'
    master.vm.box_url = "centos/stream8"

    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 2094]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "master"]
    end
  end

  config.vm.define "server1" do |server1|
    worker0.vm.box = "centos/stream8"
    worker0.vm.hostname = 'server1'
    worker0.vm.box_url = "centos/stream8"

    worker0.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "worker0"]
    end
  end

  config.vm.define "server2" do |server2|
    worker1.vm.box = "centos/stream8"
    worker1.vm.hostname = 'server2'
    worker1.vm.box_url = "centos/stream8"

    worker1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "worker1"]
    end
  end
end